
name: Deploy to ec2
on:
  push:
    branches:
      - main
jobs:
  ubuntu-jobs:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

   - name: build java application with docker
     run: sh "docker build -t jerrywise97/periodapp:v4.0


